import { categories, educationalCards, practiceQuestions } from '../data/categories.js';
import { medicines } from '../data/medicines.js';
const app=document.querySelector('#app'),side=document.querySelector('#side'),dialog=document.querySelector('#dialog'),detail=document.querySelector('#detail'),menu=document.querySelector('#menu'),close=document.querySelector('#close');
const populatedCategories=categories.filter(c=>medicines.some(m=>m.category===c.id));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const cat=id=>categories.find(c=>c.id===id);
function medicineCard(m){return `<article class="card medicine-card"><button class="med" data-med="${esc(m.id)}"><span class="pill">${esc(cat(m.category)?.name||m.category)}</span><h3>${esc(m.name)}</h3><p><b>Principio activo:</b> ${esc(m.active)}</p><div class="medicine-meta"><span>${esc(m.route)}</span><span>${esc(m.laboratory)}</span></div></button></article>`}
function categoryCard(c){const count=medicines.filter(m=>m.category===c.id).length;return `<article class="card category-card"><button class="cat" data-cat="${esc(c.id)}"><b>${esc(c.icon)}</b><strong>${esc(c.name)}</strong><p>${esc(c.description)}</p><span class="card-arrow">${count} medicamentos · Ver lista →</span></button></article>`}
function home(){return `<section class="hero"><div><span class="eyebrow">MEDSOLUTION · SOLUCIONES MÉDICAS</span><h1>AuxiFarma</h1><p>Consulta farmacéutica educativa, diseñada para funcionar offline y facilitar el estudio de pasantes.</p><div class="search"><span>⌕</span><input id="homeSearch" placeholder="Buscar medicamento o categoría…"></div></div><div class="stats"><b>${medicines.length}</b><span>medicamentos cargados</span><b>${populatedCategories.length}</b><span>categorías con medicamentos</span></div></section><section class="section"><div class="title"><h2>Categorías</h2><button class="text-link" data-route="vademecum">Ver todas →</button></div><div class="grid">${populatedCategories.map(categoryCard).join('')}</div></section>`}
function vademecum(q=''){const n=q.toLowerCase().trim();const list=populatedCategories.filter(c=>!n||`${c.name} ${c.description} ${c.keywords.join(' ')}`.toLowerCase().includes(n)||medicines.some(m=>m.category===c.id&&`${m.name} ${m.active} ${m.laboratory}`.toLowerCase().includes(n)));return `<section class="section"><span class="eyebrow">AUXIFARMA</span><h1>Vademécum</h1><p>Selecciona una categoría para consultar los medicamentos cargados.</p><div class="toolbar"><input id="search" value="${esc(q)}" placeholder="Buscar medicamento o categoría…"><span class="result-count">${medicines.length} medicamentos · ${populatedCategories.length} categorías</span></div><div id="results" class="grid">${list.length?list.map(categoryCard).join(''):'<div class="card empty">Sin resultados.</div>'}</div></section>`}
function categoryDetail(id){const c=cat(id);if(!c)return;const list=medicines.filter(m=>m.category===id);detail.innerHTML=`<span class="pill">${list.length} MEDICAMENTOS</span><h2>${esc(c.name)}</h2><p>${esc(c.description)}</p><div class="detail-list">${list.map(medicineCard).join('')}</div>`;dialog.showModal()}
function medicineDetail(id){const m=medicines.find(x=>x.id===id);if(!m)return;const c=cat(m.category);detail.innerHTML=`<span class="pill">${esc(c?.name||m.category)}</span><h2>${esc(m.name)}</h2><div class="fact-grid"><div><small>Principio activo</small><strong>${esc(m.active)}</strong></div><div><small>Vía / forma de administración</small><strong>${esc(m.route)}</strong></div><div><small>Presentaciones</small><strong>${esc(m.presentations)}</strong></div><div><small>Laboratorio</small><strong>${esc(m.laboratory)}</strong></div></div><div class="notice"><b>Fuente:</b> datos proporcionados para este proyecto. Verificar registro sanitario, presentación y condición de dispensación vigentes antes de uso profesional.</div>`;dialog.showModal()}
function education(){return `<section class="section"><span class="eyebrow">APRENDIZAJE</span><h1>Educación farmacéutica</h1><p>Tarjetas rápidas para reforzar conocimientos.</p><div class="grid">${educationalCards.map(x=>`<article class="card info"><span class="pill">CONCEPTO</span><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></article>`).join('')}</div></section>`}
function tools(){return `<section class="section"><h1>Herramientas</h1><div class="grid"><article class="card"><h3>Conversor educativo</h3><p>Conversión básica entre unidades compatibles.</p><div class="toolbar"><input id="val" type="number" placeholder="Valor"><select id="from"><option>mg</option><option>g</option><option>mL</option><option>L</option></select><select id="to"><option>g</option><option>mg</option><option>L</option><option>mL</option></select></div><button class="primary" id="convert">Convertir</button><output id="out"></output></article><article class="card"><h3>Organización de farmacia</h3><p>Tarjetas educativas sobre recepción, almacenamiento, rotación, vencimientos y cadena de frío.</p></article></div></section>`}
function practice(){const q=practiceQuestions[Math.floor(Math.random()*practiceQuestions.length)];return `<section class="section"><h1>Modo práctica</h1><article class="card practice"><span class="pill">PREGUNTA</span><h2>${esc(q[0])}</h2><button class="primary" id="answer">Mostrar respuesta</button><p id="ans" class="answer hidden">${esc(q[1])}</p><br><button class="secondary" id="next">Otra pregunta</button></article></section>`}
function about(){return `<section class="section"><article class="card info"><h1>MedSolution · Soluciones Médicas</h1><h2>AuxiFarma</h2><p>PWA educativa offline-first, modular y sin registros personales.</p><div class="notice"><b>Importante:</b> contenido educativo; verificar siempre la información oficial vigente del producto.</div></article></section>`}
function render(r){if(r==='vademecum')app.innerHTML=vademecum();else if(r==='educacion')app.innerHTML=education();else if(r==='herramientas')app.innerHTML=tools();else if(r==='practica')app.innerHTML=practice();else if(r==='acerca')app.innerHTML=about();else app.innerHTML=home();bind()}
function bind(){document.querySelectorAll('button[data-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.route));document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>categoryDetail(b.dataset.cat));const s=document.querySelector('#search');if(s)s.oninput=()=>{const q=s.value.toLowerCase().trim(),list=populatedCategories.filter(c=>!q||`${c.name} ${c.description} ${c.keywords.join(' ')}`.toLowerCase().includes(q)||medicines.some(m=>m.category===c.id&&`${m.name} ${m.active} ${m.laboratory}`.toLowerCase().includes(q)));document.querySelector('#results').innerHTML=list.length?list.map(categoryCard).join(''):'<div class="card empty">Sin resultados.</div>';document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>categoryDetail(b.dataset.cat))};const hs=document.querySelector('#homeSearch');if(hs)hs.onkeydown=e=>{if(e.key==='Enter'){location.hash='vademecum';setTimeout(()=>{const t=document.querySelector('#search');if(t){t.value=hs.value;t.dispatchEvent(new Event('input'));t.focus()}},0)}};const a=document.querySelector('#answer');if(a)a.onclick=()=>document.querySelector('#ans')?.classList.remove('hidden');const n=document.querySelector('#next');if(n)n.onclick=()=>{app.innerHTML=practice();bind()};const cv=document.querySelector('#convert');if(cv)cv.onclick=convert}
function navigate(route){side.classList.remove('open');location.hash=route}
function convert(){const v=Number(document.querySelector('#val').value),a=document.querySelector('#from').value,b=document.querySelector('#to').value,o=document.querySelector('#out');if(!Number.isFinite(v)){o.textContent='Introduce un valor.';return}const f={mg:.001,g:1,mL:.001,L:1};o.textContent=(a[0]===b[0]?(v*f[a]/f[b]).toLocaleString('es-BO'):'No se convierte masa↔volumen sin densidad o concentración.')}
menu.onclick=e=>{e.stopPropagation();side.classList.toggle('open')};side.onclick=e=>e.stopPropagation();document.addEventListener('click',()=>side.classList.remove('open'));detail.onclick=e=>{const b=e.target.closest('[data-med]');if(b)medicineDetail(b.dataset.med)};close.onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};window.addEventListener('hashchange',()=>render(location.hash.slice(1)||'inicio'));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render(location.hash.slice(1)||'inicio');
